apiVersion: v1
kind: Pod
metadata:
  name: netshoot
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot:latest
    imagePullPolicy: "Always"
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 600; done"]
