apiVersion: v1
kind: Pod
metadata:
  name: netshoot
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot:latest
    imagePullPolicy: "Always"
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 600; done"]
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 3
      failureThreshold: 1
      successThreshold: 1
