version: "3.9"

volumes:
  prometheus_etc: {}
  prometheus_data: {}

services:
  prometheus:
    container_name: prometheus
    build:
      context: .
    # need to be able to reach the locally running teleport /metrics endpoint.
    network_mode: "host"
    # ports:
    #   - "9090:9090"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: "64M"
    restart: "on-failure"
    volumes:
      - "prometheus_etc:/etc/prometheus"
      # - "prometheus_data:/prometheus_data"
    command: >-
      --config.file=/etc/prometheus/prometheus.yaml
      --storage.tsdb.retention.time=200h
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --web.enable-lifecycle

# --storage.tsdb.path=/prometheus_data
