client_encryption_options:
   enabled: true
   optional: false
   keystore: /certs/out.keystore
   keystore_password: "${PASS}"

   require_client_auth: true
   truststore: /certs/out.truststore
   truststore_password: "${PASS}"
   protocol: TLS
   algorithm: SunX509
   store_type: JKS
   cipher_suites: [TLS_RSA_WITH_AES_256_CBC_SHA]
