client_encryption_options:
   enabled: true
   optional: false
   keystore: /certs/out.keystore
   keystore_password: "3f1a89f53827a295b552cffca63a9d44fd60f18537ec3451b3a6d90a72a57ad1"

   require_client_auth: true
   truststore: /certs/out.truststore
   truststore_password: "3f1a89f53827a295b552cffca63a9d44fd60f18537ec3451b3a6d90a72a57ad1"
   protocol: TLS
   algorithm: SunX509
   store_type: JKS
   cipher_suites: [TLS_RSA_WITH_AES_256_CBC_SHA]
