version: "3.9"

networks:
  redis-cluster:
    driver: bridge

services:
  postgres:
    # container_name: postgres
    build:
      context: config/postgres
    ports:
      - "5432:5432"
  mysql:
    # container_name: mysql
    build:
      context: config/mysql
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    ports:
      - "3306:3306"
  mariadb:
    # container_name: mariadb
    build:
      context: config/mariadb
    environment:
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
    ports:
      - "3307:3306"
  mongodb:
    # container_name: mongodb
    build:
      context: config/mongodb
    ports:
      - "27017:27017"
  oracle:
    # container_name: oracle
    build:
      context: config/oracle
    environment:
      - "ENABLE_TCPS=false"
      - "ORACLE_PWD=pass"
    ports:
      - "1521:1521"
      - "2484:2484"
  cassandra:
    # container_name: cassandra
    build:
      context: config/cassandra
    ports:
    - "9042:9042"
  scylladb:
    # container_name: cassandra
    build:
      context: config/scylladb
    ports:
    - "9043:9042"
  cockroach:
    build:
      context: config/cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
  clickhouse:
    build:
      context: config/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "8443:8443"
      - "9440:9440"
  elasticsearch:
    build:
      context: config/elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
  redis:
    build:
      context: config/redis
    ports:
      - "6379:6379"
  redis-cluster:
    image: redis:latest
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      - "redis-cluster"
    environment:
      - "REDISCLI_AUTH=somepassword"
      # - "CERTS_DIR=/usr/local/etc/redis/certs/"
    command: >
      redis-cli
      -h 127.0.0.1
      -p 7001
      --user alice
      --tls --insecure
      --cluster-yes
      --cluster-replicas 1
      --cluster create
      ${HOST}:7001
      ${HOST}:7002
      ${HOST}:7003
      ${HOST}:7004
      ${HOST}:7005
      ${HOST}:7006
  redis-node-1:
    build:
      context: config/redis-cluster/build/node-1
    ports:
      - "7001:7001"
      - "17001:17001"
    networks:
      - "redis-cluster"
    hostname:
      redis-node-1
  redis-node-2:
    build:
      context: config/redis-cluster/build/node-2
    ports:
      - "7002:7002"
      - "17002:17002"
    networks:
      - "redis-cluster"
    hostname:
      redis-node-2
  redis-node-3:
    build:
      context: config/redis-cluster/build/node-3
    ports:
      - "7003:7003"
      - "17003:17003"
    networks:
      - "redis-cluster"
    hostname:
      redis-node-3
  redis-node-4:
    build:
      context: config/redis-cluster/build/node-4
    ports:
      - "7004:7004"
      - "17004:17004"
    networks:
      - "redis-cluster"
    hostname:
      redis-node-4
  redis-node-5:
    build:
      context: config/redis-cluster/build/node-5
    ports:
      - "7005:7005"
      - "17005:17005"
    networks:
      - "redis-cluster"
    hostname:
      redis-node-5
  redis-node-6:
    build:
      context: config/redis-cluster/build/node-6
    ports:
      - "7006:7006"
      - "17006:17006"
    networks:
      - "redis-cluster"
    hostname:
      redis-node-6
